import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Header from '@/components/header'

import { Inter } from 'next/font/google'

const inter = Inter({ 
  subsets: ['latin'], 
  weight: '400' 
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
         <Header>Hello World</Header>
         <p className={styles.paragraph}>I am a fonts demo</p>
      </main>
    </>
  )
}
