import Head from 'next/head'

import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import localFont from '@next/font/local';

const myFont = localFont({ src: './my-font.ttf' })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={myFont.style} className={styles.main}>
         <Header>Hello World!</Header>
         <p className={styles.paragraph}>I am a fonts demo</p>
      </main>
    </>
  )
}
